version: "3.9"

services:
  db:
    build: ./configs/confs/postgres
    restart: always
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=1440 -c log_rotation_size=0 -c log_filename='postgresql-%d.log'
    env_file:
      - .env
    volumes:
      - ./db-data/postgres_data:/var/lib/postgresql/data
      - ./db-data/postgres_backups:/backups
    ports:
      - "5433:5432"

  pass_bot:
    command: ./configs/commands/master_bot.sh
    extends:
      file: common.yml
      service: web_base
    env_file:
      - .env
    depends_on:
      - db

  web:
    command: /commands/admin.sh
    extends:
      file: common.yml
      service: web_base
    ports:
      - 8000:80
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis:7.2.0
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mounts/redis/:/data

  celery_main:
    extends:
      file: common.yml
      service: web_celery_base
    command: /commands/celery_main.sh
    depends_on:
      - redis